// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/patrick/cmd"
	"github.com/blackhorseya/patrick/internal/app/patrick/biz"
	"github.com/blackhorseya/patrick/internal/pkg/infra/log"
	"github.com/google/wire"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func CreateApp() (*cobra.Command, error) {
	command, err := cmd.NewRootCmd()
	if err != nil {
		return nil, err
	}
	return command, nil
}

// wire.go:

var providerSet = wire.NewSet(log.ProviderSet, cmd.ProviderSet, biz.ProviderSet)
