// Code generated by mockery v2.14.0. DO NOT EDIT.

package repo

import mock "github.com/stretchr/testify/mock"

// MockIProjectRepo is an autogenerated mock type for the IProjectRepo type
type MockIProjectRepo struct {
	mock.Mock
}

// WriteFile provides a mock function with given fields: filePath, tpl, data, overwrite
func (_m *MockIProjectRepo) WriteFile(filePath string, tpl []byte, data interface{}, overwrite bool) error {
	ret := _m.Called(filePath, tpl, data, overwrite)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, interface{}, bool) error); ok {
		r0 = rf(filePath, tpl, data, overwrite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockIProjectRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIProjectRepo creates a new instance of MockIProjectRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIProjectRepo(t mockConstructorTestingTNewMockIProjectRepo) *MockIProjectRepo {
	mock := &MockIProjectRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
