// Code generated by mockery v2.14.0. DO NOT EDIT.

package repo

import mock "github.com/stretchr/testify/mock"

// MockIProjectRepo is an autogenerated mock type for the IProjectRepo type
type MockIProjectRepo struct {
	mock.Mock
}

type mockConstructorTestingTNewMockIProjectRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIProjectRepo creates a new instance of MockIProjectRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIProjectRepo(t mockConstructorTestingTNewMockIProjectRepo) *MockIProjectRepo {
	mock := &MockIProjectRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
