// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func CreateRepo(logger *zap.Logger) (IProjectRepo, error) {
	iProjectRepo := NewImpl(logger)
	return iProjectRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
