// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/patrick/internal/app/patrick/api/cmd"
	"github.com/blackhorseya/patrick/internal/app/patrick/biz"
	"github.com/blackhorseya/patrick/internal/app/patrick/biz/project"
	"github.com/blackhorseya/patrick/internal/app/patrick/biz/project/repo"
	"github.com/google/wire"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func CreateApp() (*cobra.Command, error) {
	iProjectRepo := repo.NewImpl()
	iProjectBiz := project.NewImpl(iProjectRepo)
	command, err := cmd.NewRootCmd(iProjectBiz)
	if err != nil {
		return nil, err
	}
	return command, nil
}

// wire.go:

var providerSet = wire.NewSet(cmd.ProviderSet, biz.ProviderSet)
