// Code generated by mockery v2.14.0. DO NOT EDIT.

package project

import mock "github.com/stretchr/testify/mock"

// MockIProjectBiz is an autogenerated mock type for the IProjectBiz type
type MockIProjectBiz struct {
	mock.Mock
}

type mockConstructorTestingTNewMockIProjectBiz interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIProjectBiz creates a new instance of MockIProjectBiz. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIProjectBiz(t mockConstructorTestingTNewMockIProjectBiz) *MockIProjectBiz {
	mock := &MockIProjectBiz{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
