// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package project

import (
	"github.com/blackhorseya/patrick/internal/app/patrick/biz/project/repo"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateBiz(repo2 repo.IProjectRepo) (IProjectBiz, error) {
	iProjectBiz := NewImpl(repo2)
	return iProjectBiz, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
